name: SmartSpawner
version: 1.0.6
authors: [MiniMoro]
main: it.moro.smartspawner.SmartSpawner
api-version: '1.13'

commands:
  spawnerpickaxe:
    description: Give Spawner Pickaxe
    usage: /spawnerpickaxe [player]
  givespawner:
    description: Give Spawner
    usage: /givespawner [entity] [player]
  givetrialspawner:
    description: Give Spawner
    usage: /givetrialspawner [entity] [player]

permissions:
  smartspawner.*:
    description: all permissions
    default: op
    children:
      smartspawner.givespawner: true
      smartspawner.givetrialspawner: true
      smartspawner.spawnerpickaxe: true
      smartspawner.spawner.break: true
      smartspawner.spawner.place: true
      smartspawner.trialspawner.break: true
      smartspawner.trialspawner.place: true
      smartspawner.egg.use: true

  smartspawner.givespawner:
    description: Permission to use /givespawner [entity]
    default: op
  smartspawner.givetrialspawner:
    description: Permission to use /givetrialspawner [entity]
    default: op
  smartspawner.spawnerpickaxe:
    description: Permission to use /spawnerpickaxe [player]
    default: op
  smartspawner.spawner.break:
    description: Permission to collect spawner
    default: op
  smartspawner.spawner.place:
    description: Permission to place spawner
    default: op
  smartspawner.trialspawner.break:
    description: Permission to collect trial spawner
    default: op
  smartspawner.trialspawner.place:
    description: Permission to place trial spawner
    default: op
  smartspawner.egg.use:
    description: Permission to use spawn egg on spawner/trialspawner
    default: op